feat: 플레이리스트 선택 기능 추가
boostcampwm-2024/iOS06-molio pull request #137
Opened 2024-11-23 02:14 UTC by Park-kxng

## 1. 배경
- 사용자는 플레이리스트를 선택하여 노래를 저장하고 목록을 들을 수 있습니다.
- CoreData에 저장된 모든 플레이리스트를 보여줍니다.
- UserDefaults에 저장된 현재 선택된 플레이리스트를 체크 표시로 알려줍니다.
- 메인 화면에서 선택된 플레이리스트로 음악을 추가할 수 있습니다.

## 2. 작업 내용
- [x] 플레이리스트 선택 화면 UI 추가
- [x] 플레이리스트 선택 viewModel 추가
- [x] FetchAllPlaylistsUseCase 추가 
- [x] 새로운 플레이리스트 생성하고 다시 선택화면으로 돌아왔을 때 데이터 리로드 기능 추가

## 3. 스크린샷

|   SE   |   15PRO   | 
| :-------------: |  :-------------: |
| <img width=200 src="https://github.com/user-attachments/assets/f62460bd-60e0-4b63-b942-ab25fabbe9b3"> | <img width=200 src="https://github.com/user-attachments/assets/348fde97-89d6-4314-8e07-6788cea92475"> | 

### 시연 영상
- 시나리오 1 : 플레이리스트를 선택합니다. -> 메인 화면에 반영되는 것을 확인합니다.
- 시나리오 2 : 플레이리스트를 새로 생성하면 목록에 반영됩니다.
https://github.com/user-attachments/assets/1e6eee76-9789-4339-ac2c-3608bedc153a

### 4. Issue 번호

Resolved #96
Resolved #99

2024-11-23 11:53 UTC, alstn38 approved these changes
고생많으셨습니다 !! 👍👍👍
다른 플리를 선택하면 바로 메인화면에 적용되는 것으로 예상했는데 sheet를 내려야지 적용이 되는것으로 보입니다!! 이부분은 추후에 개선해보면 좋을 것 같아요!!

2024-11-23 11:53 UTC, alstn38 commented on Molio/Source/Domain/Entity/MolioPlaylist.swift
>      let createdAt: Date
P3: Identifiable 프로토콜은 어떤상황에서 필요해서 작성된건지 알려주실수있나요??

2024-11-23 11:53 UTC, alstn38 commented on Molio/Source/Domain/UseCase/FetchAllPlaylistsUseCase/DefaultFetchAllPlaylistsUseCase.swift
> +    }
P3:
```swift
func execute() async -> [MolioPlaylist] {
    return playlistRepository.fetchPlaylists() ?? []
}
```
이런식으로 작성하면 안되나요??

2024-11-23 11:53 UTC, alstn38 commented on Molio/Source/Presentation/SelectPlaylist/SelectPlaylistView.swift
> +    var placeholder: String = "00님의 몰리오"
P3: 해당 프로퍼티는 사용되지 않고 있는 것으로 보입니다.

2024-11-23 11:53 UTC, alstn38 commented on Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
> +
P3: 이와같이 selectedPlaylistTitleLabel.text에 바로 대입해도 근영님께서 설정하신 Font가 제대로 적용되는지 혹시 한번 확인해주실 수 있나요? 만약 적용되지 않는다면
selectedPlaylistTitleLabel.molioMedium(text: playlist.name, size: 16)과 같이 적용할 수 있겠군요!

2024-11-23 11:53 UTC, alstn38 commented on Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
> +        label.molioMedium( text: "", size: 16)
P3: label.molioMedium( text: "", size: 16)
( )text: << Argument Label 앞에 빈 공백이 있습니다.

2024-11-23 11:53 UTC, alstn38 commented on Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
> +        let selectplaylistView = SelectPlaylistView(viewModel: SelectPlaylistViewModel())
P3: TODO 적용해주셔서 감사합니다! 혹시 적용이 된 TODO는 지워주실수있나요??

2024-11-23 11:54 UTC, alstn38 approved these changes

2024-11-23 11:54 UTC, alstn38 commented on Molio/Source/Presentation/SelectPlaylist/SelectPlaylistView.swift
> +                Text("그냥님의 몰리오")
P3: placeholder가 아마 이쪽으로 수정하려고 계획했었나요?? 이후 사용자 이름을 받아오는 것을 TODO로 작성해놓으면 좋을 것 같습니다 !!

2024-11-23 12:34 UTC, kybeen requested changes
수고하셨습니다!!

코드를 살펴보다 궁금한 점이 생겨서 코멘트를 남겨봤습니다!
팀 차원에서 계층 별 로직을 연결하는 방식이 정리가 제대로 안된 것 같아서, 내일 인터페이스를 합치면서 같이 얘기해보면 좋을 것 같아요ㅎㅎ

해당 PR 테스트 코드에서 에러가 발생하고 있는데, 이 부분도 확인 부탁드립니다!

2024-11-23 12:34 UTC, kybeen commented on Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
>      private let musicCardSwipeAnimationPublisher = PassthroughSubject<SwipeDirection, Never>()
P3;
의존하는 객체들과 퍼블리셔는 공백으로 구분해주면 덜 헷갈릴 것 같네요!
``` suggestion
    private let musicDeck: any MusicDeck
    private let fetchImageUseCase: FetchImageUseCase
    private let publishCurrentPlaylistUseCase: PublishCurrentPlaylistUseCase

    private let selectedPlaylistPublisher = PassthroughSubject<MolioPlaylist, Never>()
    private let isLoadingPublisher = PassthroughSubject<Bool, Never>()
    private let buttonHighlightPublisher = PassthroughSubject<ButtonHighlight, Never>()
    private let musicCardSwipeAnimationPublisher = PassthroughSubject<SwipeDirection, Never>()
```

2024-11-23 12:34 UTC, kybeen commented on Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
>          }
P3;
비동기 메서드로 변경된 이유와 `continuation`이 사용된 이유가 궁금합니다!

2024-11-23 12:34 UTC, kybeen commented on Molio/Source/Presentation/SelectPlaylist/SelectPlaylistViewModel.swift
P2;
코드를 읽어보다 동작 방식에서 궁금한 점이 생겼습니다!

`SelectedPlaylistView`에서 모달 시트가 닫히면 뷰모델의 `reload()`가 호출되는데,
뷰모델의 `reload()` 함수 내부를 보면 **`publishCurrentPlaylistUseCase.execute()` 실행에 대한 구독이 추가되는 형식** 인 것 같습니다.
그렇다면 reload할 때마다 중복되는 구독이 계속 추가된다는 뜻인 것 같은데, 해당 방식이 자연스러워보이지는 않아서 내일 얘기를 해보는게 좋을 것 같습니다!

`selectedPlaylist`는 값이 수정될 때마다 이벤트를 방출하는데,
`reload()`시에는 그냥 현재 플레이리스트 정보를 불러와서 `selectedPlaylist`에 새로운 플레이리스트 값만 할당 해주면 되지 않나? 하는 생각이 들었습니다.
> 👉 `fetchPlaylists()` 메서드에서 `playlists`를 갱신하는 로직과 동일하게 처리해도 될 것 같은데, 서로 내부 구현 방식이 달라서 코멘트 남겨봤습니다!

2024-11-24 01:55 UTC, windowcow commented on Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
>          }
withCheckedContinuation을 왜 쓰셨나 했더니 콜백 기반 비동기 코드를 async await으로 바꾸기 위해서 사용하셨군요
복잡했을텐데 수고하셨습니다

2024-11-24 01:59 UTC, windowcow commented on Molio/Source/Domain/UseCase/FetchAllPlaylistsUseCase/DefaultFetchAllPlaylistsUseCase.swift
> +    }
```suggestion
    func execute() async -> [MolioPlaylist] {
        return await self.playlistRepository.fetchPlaylists() 
    }
```

맞습니다. 이 부분에서 사용되는 콜백 기반 비동기 코드가 없는 만큼.
 이렇게 쓰시면 어떨까요?

2024-11-24 02:02 UTC, windowcow commented on Molio/Source/Presentation/SelectPlaylist/SelectPlaylistViewModel.swift
> +        }
```suggestion
        Task { @MainActor in
            self.playlists = await fetchAllPlaylistsUseCase.execute()
        }
```
이렇게 사용하시면 어떨까요? 어차피 await 뒤에 있는 fetchAllPlaylistsUseCase.execute는 다른 스레드 (Main이 아닌 스레드)에서 실행됩니다.

2024-11-24 02:19 UTC, windowcow approved these changes
수고하셨습니다!

2024-11-25 05:23 UTC, Park-kxng commented on Molio/Source/Presentation/SelectPlaylist/SelectPlaylistView.swift
> +    var placeholder: String = "00님의 몰리오"
네 맞습니다 삭제하겠습니다

2024-11-25 05:23 UTC, Park-kxng commented on Molio/Source/Presentation/SelectPlaylist/SelectPlaylistView.swift
> +                Text("그냥님의 몰리오")
넵 추가하겠습니다!

2024-11-25 05:23 UTC, Park-kxng commented on Molio/Source/Domain/UseCase/FetchAllPlaylistsUseCase/DefaultFetchAllPlaylistsUseCase.swift
> +    }
비동기로 바꿀 가능성이 있기 때문에 이렇게 구현하였습니다. 현재 playlistService 프로토콜에도 async throws 적용될 것 같은데 그냥 돠두고 PlaylistService 작성할 때 바꾸는 건 어떨까요???????

2024-11-25 05:23 UTC, Park-kxng commented on Molio/Source/Domain/Entity/MolioPlaylist.swift
>      let createdAt: Date
List나 ForEach는 데이터 소스를 기반으로 UI를 생성합니다. 데이터 소스의 각 항목을 고유하게 식별해야 렌더링 및 업데이트가 가능해집니다. 그래서 identitiable을 채택해줘야 고유하게 식별이 가능하다고 합니다. 현재 id를 기반으로 뷰를 확인하고 표시하고 있습니다.

2024-11-25 05:23 UTC, Park-kxng commented on Molio/Source/Presentation/SelectPlaylist/SelectPlaylistViewModel.swift
중복되는 코드를 넣자는 생각에 아무 생각없이 같이 묶어버렸네요. 말씀하시는 부분은 수정이 필요할 것 같습니다.!

2024-11-25 05:23 UTC, Park-kxng commented on Molio/Source/Presentation/SelectPlaylist/SelectPlaylistViewModel.swift
> +        }
viewModel 과 이 코드가 연결되어 있어서인지 메인 스레드에서 실행된다는 오류가 발생하여 이렇게 작성하였습니다. 다시 알아보겠습니다.

2024-11-25 05:23 UTC, Park-kxng commented on Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
> +
이미 폰트는 반영해주신것 같아서 텍스트 내용만 변경하도록 하였습니다. 적용되는지 확인해보겠습니다.

2024-11-25 05:23 UTC, Park-kxng commented on Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
> +        let selectplaylistView = SelectPlaylistView(viewModel: SelectPlaylistViewModel())
이 부분은 아직 적용이 안돼서 수정 안했습니다. 하지만 DI container를 사용하지 않을 것 같아 삭제하겠습니다.

2024-11-25 05:23 UTC, Park-kxng commented on Molio/Source/Presentation/SwipeMusic/ViewModel/SwipeMusicViewModel.swift
>      private let musicCardSwipeAnimationPublisher = PassthroughSubject<SwipeDirection, Never>()
넵 반영하겠습니다!

2024-11-25 05:28 UTC, Park-kxng commented on Molio/Source/Presentation/SwipeMusic/View/SwipeMusicViewController.swift
> +
![image](https://github.com/user-attachments/assets/597813b7-6b8a-440a-9303-d3a952f0950e)
적용되는 것 확인했습니다

2024-11-25 05:33 UTC, Park-kxng commented on Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
>          }
비동기는 추후에 파이어베이스가 들어오게 되면 수정될 것 같아서 변경하였습니다. 제대로 데이터가 불러와지지 않는 이슈가 발생해 다양한 방안을 적용해보았습니다. withCheckedContinuation은 Swift의 async/await 환경에서 기존 콜백 기반 작업을 비동기 코드로 변환할 때 사용됩니다. Core Data 작업은 여전히 콜백 스타일(context.perform)로 동작하므로, 이를 async 메서드로 바꿔주는 데 사용되었습니다.

2024-11-25 05:34 UTC, Park-kxng commented on Molio/Source/Data/Repository/DefaultPlaylistRepository.swift
>          }
맞습니다!!!!!! @kybeen 위에 영빈님이 질문 남겨주신 부분에 답변이 될 수도 있을 것 같습니다.

2024-11-25 05:38 UTC, Park-kxng commented on Molio/Source/Presentation/SelectPlaylist/SelectPlaylistViewModel.swift
> +        }
창우님 코드 적용했습니다! mainActor에 대해 공부해보겠습니다

2024-11-25 05:52 UTC, windowcow commented on Molio/Source/Presentation/SelectPlaylist/SelectPlaylistViewModel.swift
> +        }
감사합니다!!

2024-11-25 06:03 UTC, kybeen approved these changes

2024-11-25 06:53 UTC, windowcow commented on Molio/Source/Domain/UseCase/FetchAllPlaylistsUseCase/DefaultFetchAllPlaylistsUseCase.swift
> +    }
비동기 코드인 거랑 withCheckedContinuation를 사용하는 것이랑 무슨 상관인지 모르겠습니다. 혹시 withCheckedContinuation 어떨 때 사용하는지 잘 아시고 쓰시는 걸까요?

2024-11-25 07:51 UTC, merged